# Generated by Django 6.0.4 on 2026-05-09 15:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, help_text='EAN/UPC barcode if available.', max_length=64, null=True, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('colour_name', models.CharField(blank=True, max_length=120)),
                ('shade_code', models.CharField(blank=True, max_length=80)),
                ('item_type', models.CharField(choices=[('consumable', 'Consumable'), ('equipment', 'Equipment'), ('tool', 'Tool'), ('disposable', 'Disposable'), ('other', 'Other')], default='consumable', max_length=30)),
                ('category', models.CharField(choices=[('gel_polish', 'Gel Polish'), ('builder_gel', 'Builder Gel / BIAB'), ('base_coat', 'Base Coat'), ('top_coat', 'Top Coat'), ('acrylic', 'Acrylic'), ('gel_x', 'Gel-X'), ('nail_art', 'Nail Art'), ('prep', 'Prep / Cleaner'), ('removal', 'Removal'), ('disposable', 'Disposable'), ('equipment', 'Equipment'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=40)),
                ('unit_type', models.CharField(choices=[('bottle', 'Bottle'), ('tube', 'Tube'), ('pot', 'Pot'), ('box', 'Box'), ('pack', 'Pack'), ('piece', 'Piece'), ('tool', 'Tool'), ('other', 'Other')], default='bottle', max_length=30)),
                ('size_value', models.DecimalField(blank=True, decimal_places=2, help_text='Example: 5, 10, 100', max_digits=8, null=True)),
                ('size_unit', models.CharField(choices=[('ml', 'ml'), ('g', 'g'), ('pcs', 'pcs'), ('set', 'set'), ('other', 'Other')], default='ml', max_length=20)),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_stock_alert', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per item/unit bought.', max_digits=10, null=True)),
                ('estimated_uses_per_item', models.PositiveIntegerField(blank=True, help_text='Example: 40 pairs of hands from one bottle.', null=True)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('issuing_country', models.CharField(blank=True, help_text='Example: CN from EAN lookup.', max_length=10)),
                ('external_lookup_source', models.CharField(blank=True, help_text='Example: EAN-Search, manual, OCR.', max_length=120)),
                ('ocr_extracted_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_name', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('add', 'Add Stock'), ('use', 'Use Stock'), ('adjust', 'Adjustment'), ('waste', 'Waste / Damaged'), ('archive', 'Archived')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
