# Generated by Django 6.0.4 on 2026-04-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nailservice',
            name='service_area',
            field=models.CharField(choices=[('nails', 'Nails'), ('toes', 'Toes')], default='nails', max_length=20),
        ),
    ]
