# Generated by Django 6.0.4 on 2026-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cash_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='colour_notes',
            field=models.TextField(default='No details provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Pay cash at appointment')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='vibe_notes',
            field=models.TextField(default='No details provided'),
            preserve_default=False,
        ),
    ]
