# Generated by Django 6.0.4 on 2026-04-29 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_cash_confirmed_booking_colour_notes_and_more'),
        ('services', '0002_nailservice_service_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='notes',
            new_name='nail_colour_notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='colour_notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vibe_notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('nails', 'Nails'), ('toes', 'Toes'), ('both', 'Nails and Toes')], default='nails', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='nail_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nail_bookings', to='services.nailservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='nail_vibe_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='toe_colour_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='toe_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='toe_bookings', to='services.nailservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='toe_vibe_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
